# Generated by Django 4.2.10 on 2026-06-21 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerbBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批次编号')),
                ('herb_name', models.CharField(max_length=100, verbose_name='药材名称')),
                ('initial_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='初始重量(g)')),
                ('required_rounds', models.PositiveIntegerField(default=9, verbose_name='规定轮次')),
                ('status', models.CharField(choices=[('pending', '待炮制'), ('processing', '炮制中'), ('completed', '待验收'), ('accepted', '已验收')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '药材批次',
                'verbose_name_plural': '药材批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', '合格'), ('fail', '不合格'), ('reprocess', '返工')], max_length=20, verbose_name='验收结果')),
                ('remark', models.TextField(verbose_name='验收备注')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='验收时间')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='herbapp.herbbatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '质量验收',
                'verbose_name_plural': '质量验收',
            },
        ),
        migrations.CreateModel(
            name='ProcessingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(verbose_name='轮次序号')),
                ('steam_time', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='蒸制时间(分钟)')),
                ('dry_duration', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='晾晒时长(小时)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前重量(g)')),
                ('color_rating', models.CharField(choices=[('excellent', '优'), ('good', '良'), ('normal', '中'), ('abnormal', '异常')], max_length=20, verbose_name='色泽评级')),
                ('handling_opinion', models.TextField(blank=True, null=True, verbose_name='处理意见')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='herbapp.herbbatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '炮制轮次',
                'verbose_name_plural': '炮制轮次',
                'ordering': ['batch', 'round_no'],
                'unique_together': {('batch', 'round_no')},
            },
        ),
    ]
