# Generated by Django 4.2.10 on 2026-06-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStandardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('herb_name', models.CharField(max_length=100, verbose_name='适用药材')),
                ('total_rounds', models.PositiveIntegerField(default=9, verbose_name='总轮次数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '炮制标准模板',
                'verbose_name_plural': '炮制标准模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='processinground',
            name='abnormal_reasons',
            field=models.JSONField(blank=True, default=dict, verbose_name='异常原因详情'),
        ),
        migrations.AddField(
            model_name='processinground',
            name='is_abnormal',
            field=models.BooleanField(default=False, verbose_name='是否异常'),
        ),
        migrations.AddField(
            model_name='processinground',
            name='review_result',
            field=models.TextField(blank=True, null=True, verbose_name='复核结果'),
        ),
        migrations.AddField(
            model_name='processinground',
            name='review_status',
            field=models.CharField(choices=[('pending', '待复核'), ('pass', '通过'), ('reject', '驳回')], default='pending', max_length=20, verbose_name='复核状态'),
        ),
        migrations.AddField(
            model_name='processinground',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复核时间'),
        ),
        migrations.AddField(
            model_name='processinground',
            name='reviewer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='复核人'),
        ),
        migrations.CreateModel(
            name='BatchQualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight_loss_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='总重量损耗率(%)')),
                ('avg_color_score', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='平均色泽评分')),
                ('abnormal_count', models.PositiveIntegerField(default=0, verbose_name='异常次数')),
                ('abnormal_details', models.JSONField(blank=True, default=list, verbose_name='异常详情列表')),
                ('steam_time_deviation', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='蒸制时间偏差率(%)')),
                ('dry_duration_deviation', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='晾晒时长偏差率(%)')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='最终评分(满分100)')),
                ('overall_grade', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('normal', '合格'), ('poor', '不合格')], default='normal', max_length=20, verbose_name='综合评级')),
                ('evaluator', models.CharField(blank=True, max_length=50, null=True, verbose_name='评估人')),
                ('evaluation_remark', models.TextField(blank=True, null=True, verbose_name='评估备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessment', to='herbapp.herbbatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '批次质量总评',
                'verbose_name_plural': '批次质量总评',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='herbbatch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='herbapp.processingstandardtemplate', verbose_name='引用标准模板'),
        ),
        migrations.CreateModel(
            name='RoundStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(verbose_name='轮次序号')),
                ('steam_time_min', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='蒸制时间下限(分钟)')),
                ('steam_time_max', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='蒸制时间上限(分钟)')),
                ('dry_duration_min', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='晾晒时长下限(小时)')),
                ('dry_duration_max', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='晾晒时长上限(小时)')),
                ('weight_loss_max', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='最大允许重量损耗(%)')),
                ('required_color', models.CharField(choices=[('excellent', '优'), ('good', '良以上'), ('normal', '中以上')], default='good', max_length=20, verbose_name='色泽要求')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_standards', to='herbapp.processingstandardtemplate', verbose_name='所属模板')),
            ],
            options={
                'verbose_name': '轮次标准',
                'verbose_name_plural': '轮次标准',
                'ordering': ['template', 'round_no'],
                'unique_together': {('template', 'round_no')},
            },
        ),
    ]
