# Generated by Django 4.2.10 on 2026-06-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbapp', '0002_processingstandardtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='是否当前版本'),
        ),
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='master_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='主记录ID'),
        ),
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='version_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='版本号'),
        ),
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='version_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='版本创建时间'),
        ),
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='version_created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='版本创建人'),
        ),
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='version_major',
            field=models.PositiveIntegerField(default=1, verbose_name='主版本号'),
        ),
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='version_minor',
            field=models.PositiveIntegerField(default=0, verbose_name='次版本号'),
        ),
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='version_remark',
            field=models.TextField(blank=True, null=True, verbose_name='版本说明'),
        ),
        migrations.AddField(
            model_name='processingstandardtemplate',
            name='version_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('obsolete', '已废弃')], default='approved', max_length=20, verbose_name='版本状态'),
        ),
        migrations.AlterField(
            model_name='processingstandardtemplate',
            name='template_name',
            field=models.CharField(max_length=100, verbose_name='模板名称'),
        ),
    ]
