# Generated by Django 4.2.10 on 2026-06-21 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herbapp', '0002_processingstandardtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb_name', models.CharField(max_length=100, verbose_name='适用药材')),
                ('param_type', models.CharField(choices=[('temperature', '温度'), ('humidity', '湿度')], max_length=20, verbose_name='参数类型')),
                ('stage', models.CharField(choices=[('steam', '蒸制阶段'), ('dry', '晾晒阶段'), ('both', '全部阶段')], default='both', max_length=20, verbose_name='适用阶段')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='最小值')),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='最大值')),
                ('unit', models.CharField(default='', max_length=10, verbose_name='单位')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '环境参数标准',
                'verbose_name_plural': '环境参数标准',
                'ordering': ['herb_name', 'param_type', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_no', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('equipment_type', models.CharField(choices=[('steamer', '蒸制设备'), ('drying_rack', '晾晒架'), ('other', '其他设备')], max_length=20, verbose_name='设备类型')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格型号')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='生产厂家')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购置日期')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='存放位置')),
                ('status', models.CharField(choices=[('normal', '正常'), ('maintenance', '维护中'), ('fault', '故障'), ('scrapped', '已报废')], default='normal', max_length=20, verbose_name='设备状态')),
                ('capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='额定容量')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次维护日期')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='设备说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'ordering': ['equipment_type', 'equipment_no'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('daily', '日常巡检'), ('before', '生产前检查'), ('after', '生产后检查'), ('special', '专项巡检')], max_length=20, verbose_name='巡检类型')),
                ('inspection_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='巡检时间')),
                ('inspector', models.CharField(max_length=50, verbose_name='巡检人')),
                ('inspection_items', models.JSONField(blank=True, default=list, verbose_name='巡检项目')),
                ('inspection_result', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常'), ('pending', '待确认')], default='pending', max_length=20, verbose_name='巡检结果')),
                ('abnormal_description', models.TextField(blank=True, null=True, verbose_name='异常说明')),
                ('handling_result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('handling_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理人')),
                ('handling_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='巡检图片')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='herbapp.herbbatch', verbose_name='所属批次')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to='processing.equipment', verbose_name='巡检设备')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'ordering': ['-inspection_time'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联轮次')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('running_status', models.CharField(choices=[('running', '运行中'), ('standby', '待机'), ('stopped', '停机'), ('fault', '故障')], max_length=20, verbose_name='运行状态')),
                ('operating_params', models.JSONField(blank=True, default=dict, verbose_name='运行参数')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('abnormal_description', models.TextField(blank=True, null=True, verbose_name='异常说明')),
                ('handling_result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人员')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_records', to='herbapp.herbbatch', verbose_name='所属批次')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_records', to='processing.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备状态记录',
                'verbose_name_plural': '设备状态记录',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联轮次')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='温度(°C)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='湿度(%RH)')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='监测位置')),
                ('recorder', models.CharField(blank=True, max_length=50, null=True, verbose_name='记录人')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('abnormal_details', models.JSONField(blank=True, default=dict, verbose_name='异常详情')),
                ('handling_opinion', models.TextField(blank=True, null=True, verbose_name='处理意见')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_records', to='herbapp.herbbatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '环境监测记录',
                'verbose_name_plural': '环境监测记录',
                'ordering': ['-record_time'],
            },
        ),
        migrations.CreateModel(
            name='DryingAreaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联轮次')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('area_name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('area_type', models.CharField(choices=[('sunshine', '阳光晾晒区'), ('shade', '阴干区'), ('ventilated', '通风区'), ('constant_temp', '恒温区')], max_length=20, verbose_name='区域类型')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='区域温度(°C)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='区域湿度(%RH)')),
                ('light_intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='光照强度(Lux)')),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='风速(m/s)')),
                ('ventilation_condition', models.CharField(blank=True, max_length=200, null=True, verbose_name='通风情况')),
                ('position_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='具体位置')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('abnormal_details', models.JSONField(blank=True, default=dict, verbose_name='异常详情')),
                ('handling_opinion', models.TextField(blank=True, null=True, verbose_name='处理意见')),
                ('recorder', models.CharField(blank=True, max_length=50, null=True, verbose_name='记录人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drying_records', to='herbapp.herbbatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '晾晒区域记录',
                'verbose_name_plural': '晾晒区域记录',
                'ordering': ['-record_time'],
            },
        ),
    ]
